apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/project-default: "true"
        io.kompose.service: auth-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: users
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: EX_PORT
              value: "8080"
          image: gcr.io/mdm-mx/auth-service:latest
          name: auth-service
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
      restartPolicy: Always
