apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: device-service
  name: device-service
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 80
  selector:
    io.kompose.service: device-service
