version: '3.8'
services:

  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: secure_sync
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  # -----------------------------
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  auth-service:
    image: gcr.io/mdm-mx/auth-service:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_NAME: users
      EX_PORT: 8080
  mail-service:
    image: gcr.io/mdm-mx/mail-service:latest
    ports:
      - "8081:80"
    restart: always
    environment:
      EMAIL_DOMAIN: email
      EMAIL_PASSWORD: password
      EX_PORT: 8081
  policy-service:
    image: gcr.io/mdm-mx/policy-service:latest
    ports:
      - "8083:80"
    restart: always
    environment:
      EX_PORT: 8083
  device-service:
    image: gcr.io/mdm-mx/device-service:latest
    ports:
      - "8084:80"
    restart: always
    environment:
      EX_PORT: 8084
  enrollment-service:
    image: gcr.io/mdm-mx/enrollment-service:latest
    ports:
      - "8085:80"
    restart: always
    environment:
      EX_PORT: 8085
volumes:
  postgres_data:
  # mongodb_data:
