apiVersion: v1
kind: Service
metadata:
  name: unified-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: unified
  ports:
    - name: auth-service
      port: 8080
      targetPort: 8080
    - name: configuration-service
      port: 8087
      targetPort: 8087
    - name: device-service
      port: 8084
      targetPort: 8084
    - name: enrollment-service
      port: 8085
      targetPort: 8085
    - name: mail-service
      port: 8081
      targetPort: 8081
    - name: policy-service
      port: 8083
      targetPort: 8083
