# Build stage
FROM --platform=linux/amd64 golang:alpine AS build-env

# Add ca-certificates in case you need to make HTTPS calls
RUN apk --no-cache add ca-certificates

# Set up dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy in the source code and build the binary.
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o auth-service ./cmd/main.go

# Final stage
FROM --platform=linux/amd64 alpine:latest

# Copy the binary from the build stage.
COPY --from=build-env /go/auth-service /auth-service

# Run the service
CMD ["/auth-service"]