FROM golang:1.21 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .


RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o enrollment-service ./cmd/main.go


FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /root/


COPY --from=builder /app/enrollment-service .


COPY tokens ./tokens/





CMD ["./enrollment-service"]
