FROM golang:1.21 as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .


RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o mail-service ./cmd/app.go


FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /root/


COPY --from=builder /app/mail-service .




COPY tokens ./tokens/
CMD ["./mail-service"]